"""
connectivity_engine.py
----------------------
Satellite communications, VSAT tracking, atmospheric attenuation,
radome icing/de-icing dynamics, and store-and-forward data buffering.

Antarctica Digital Twin | SIH Project
"""

import math
import random
from typing import Dict, Any


def initialize_connectivity() -> Dict[str, Any]:
    """Create persistent telecommunications state for a station."""
    return {
        "offline_days": 0,
        "buffered_data_mb": 0.0,
        "outage_count": 0,
        "last_status": "ONLINE",
        "max_outage_days": 0,
        "radome_ice_penalty": 0.0,
    }


def simulate_connectivity(
    weather: Dict[str, Any],
    state: Dict[str, Any] = None,
    vsat_hardware_status: str = "OPERATIONAL",
) -> Dict[str, Any]:
    """
    Simulate satellite link attenuation, storm outages, and data backlog.
    """
    state = state if state is not None else initialize_connectivity()

    weather_type = weather.get("weather_type", "NORMAL")
    wind_speed = weather.get("wind_speed_kmh", 20.0)
    severity = weather.get("weather_severity", 10.0)

    # Base link quality as a function of weather regime
    base_quality_map = {
        "CLEAR": 0.96,
        "NORMAL": 0.88,
        "HIGH_WIND": 0.65,
        "HEAVY_SNOW": 0.45,
        "WHITEOUT": 0.22,
        "BLIZZARD": 0.06,
    }
    raw_quality = base_quality_map.get(weather_type, 0.85)

    # Accumulate radome ice during blizzards/heavy snow
    if weather_type in {"BLIZZARD", "HEAVY_SNOW", "WHITEOUT"}:
        state["radome_ice_penalty"] = min(0.60, state.get("radome_ice_penalty", 0.0) + 0.25)
    else:
        # Radome de-icing heaters gradually melt ice in clear weather
        state["radome_ice_penalty"] = max(0.0, state.get("radome_ice_penalty", 0.0) - 0.30)

    effective_quality = max(0.02, min(0.99, raw_quality - state["radome_ice_penalty"]))

    # Determine link operational status
    if vsat_hardware_status in {"FAILED", "MAINTENANCE"}:
        status = "OFFLINE"
    elif weather_type == "BLIZZARD" and (random.random() < 0.85 or wind_speed > 95.0):
        status = "OFFLINE"
    elif weather_type == "WHITEOUT" and random.random() < 0.50:
        status = "OFFLINE"
    elif effective_quality < 0.30:
        status = "LIMITED"  # Low-bandwidth Iridium fallback
    elif effective_quality < 0.60:
        status = "DEGRADED"
    else:
        status = "ONLINE"

    # Daily data generated by scientific instruments & IoT sensors (~150 MB/day)
    daily_generated_data = round(random.uniform(120.0, 180.0), 2)
    buffer_uploaded = 0.0

    if status == "OFFLINE":
        state["offline_days"] += 1
        state["outage_count"] += int(state["last_status"] != "OFFLINE")
        state["buffered_data_mb"] = round(state["buffered_data_mb"] + daily_generated_data, 2)
    else:
        if state["offline_days"] > 0:
            state["max_outage_days"] = max(state["max_outage_days"], state["offline_days"])
        state["offline_days"] = 0

        # Upload bandwidth available to flush backlog
        upload_rate = 600.0 if status == "ONLINE" else (150.0 if status == "DEGRADED" else 30.0)
        flush_amount = min(state["buffered_data_mb"], upload_rate)
        state["buffered_data_mb"] = round(max(0.0, state["buffered_data_mb"] - flush_amount), 2)
        buffer_uploaded = flush_amount

        if status != "ONLINE":
            state["buffered_data_mb"] = round(state["buffered_data_mb"] + (daily_generated_data * 0.50), 2)

    state["last_status"] = status

    # Bandwidth (Mbps), Latency (ms), and Packet Loss (%)
    bandwidth = round(35.0 * effective_quality, 2) if status != "OFFLINE" else 0.0
    latency = round(520 + (1.0 - effective_quality) * 4500) if status != "OFFLINE" else 9999
    packet_loss = round((1.0 - effective_quality) * 35.0, 2) if status != "OFFLINE" else 100.0

    sync_mode = (
        "REALTIME" if status == "ONLINE" else
        ("PERIODIC" if status == "DEGRADED" else "STORE_AND_FORWARD")
    )

    return {
        "connectivity_status": status,
        "bandwidth_mbps": bandwidth,
        "latency_ms": latency,
        "packet_loss_percent": packet_loss,
        "sync_mode": sync_mode,
        "buffered_data_mb": round(state["buffered_data_mb"], 2),
        "offline_duration_days": state["offline_days"],
        "signal_quality_percent": round(effective_quality * 100.0, 2),
        "buffer_uploaded_today_mb": round(buffer_uploaded, 2),
        "communication_outage_event": (status == "OFFLINE" and state["offline_days"] == 1),
    }
