"""
leakage_audit.py
----------------
Exhaustive scientific leakage audit for Model 3 (Fuel Runway Forecast V3).
Audits all candidate variables against the 18:00 cutoff contract on Day t
predicting fuel_days_remaining for Day t+1.

Classifications:
  - Historical:           Observed operational telemetry strictly on or before Day t
  - Forecast Available:   NWP / astronomical forecast known in advance for Day t+1
  - Leakage:              Same-day realized outcome unknown until Day t+1 concludes
  - Simulator Arithmetic: Computed directly from or with target inside the simulator
  - Target Derived:       Algebraic transformation of or ratio with the target variable
  - Unknown:              Ambiguous timing — rejected by default
"""

import os
import pandas as pd

AUDIT_RULES = [
    # ── DIRECT TARGET SELF-REFERENCE & ALGEBRAIC IDENTITIES ───────────────────
    ("fuel_days_remaining", "Target Derived",
     "The raw target itself. Must be shifted to Day t+1 to serve as the forecast predictand. Cannot appear in features.",
     "REMOVE FROM FEATURES"),
    ("fuel_consumed_today_liters (Day t+1)", "Leakage",
     "Same-day realized fuel burn on Day t+1. This is the denominator of the target formula: fuel_stock / fuel_consumed. Realized after Day t+1 finishes.",
     "REJECT"),
    ("fuel_days_remaining = fuel_stock / fuel_consumed", "Target Derived",
     "The exact algebraic identity defining the target. Using fuel_consumed (today) to compute fuel_days_remaining is direct target encoding.",
     "REJECT (Use rolling consumption lags instead)"),
    ("fuel_efficiency_l_per_kwh", "Target Derived",
     "Post-hoc ratio: fuel_consumed / generator_energy. Computed after Day t+1 concludes. Encodes same-day fuel consumption.",
     "REJECT"),

    # ── SAME-DAY GENERATOR DISPATCH & ENERGY OUTCOMES (DAY t+1 LEAKAGE) ──────
    ("generator_output_kw (Day t+1)", "Leakage",
     "Electrical dispatch during Day t+1. Unknown at 18:00 on Day t. Drives same-day fuel burn equation.",
     "REJECT"),
    ("generator_runtime_hours (Day t+1)", "Leakage",
     "Genset operating hours during Day t+1. Realized after Day t+1 finishes.",
     "REJECT"),
    ("active_generators (Day t+1)", "Leakage",
     "Number of staging units during Day t+1. Same-day dispatch decision.",
     "REJECT"),
    ("gen_utilization_pct (Day t+1)", "Leakage",
     "Generator load factor during Day t+1. Drives SFC non-linearity in simulator.",
     "REJECT"),
    ("gen_energy_proxy (Day t+1)", "Simulator Arithmetic",
     "output_kw * runtime_hours on Day t+1. Primary driver of fuel consumption in SFC equation.",
     "REJECT"),
    ("generator_energy_kwh (Day t+1)", "Simulator Arithmetic",
     "Integrated electrical generation dispatched to serve load on Day t+1.",
     "REJECT"),
    ("daily_load_energy_kwh (Day t+1)", "Simulator Arithmetic",
     "Total electrical load energy on Day t+1. Determines generator dispatch and fuel burn.",
     "REJECT"),
    ("generator_status (Day t+1)", "Leakage",
     "Post-event operational classification assigned based on Day t+1 dispatch.",
     "REJECT"),

    # ── SAME-DAY ELECTRICAL LOAD REALIZATIONS (DAY t+1 LEAKAGE) ──────────────
    ("total_load_kw (Day t+1)", "Leakage",
     "Realized total electrical demand on Day t+1. Unknown until Day t+1 concludes.",
     "REJECT"),
    ("heating_load_kw (Day t+1)", "Leakage",
     "Electrical heating draw on Day t+1. Direct sub-component of total load.",
     "REJECT"),
    ("accommodation_load_kw (Day t+1)", "Leakage",
     "Sub-load component on Day t+1. Summing sub-loads yields total load.",
     "REJECT"),
    ("laboratory_load_kw (Day t+1)", "Leakage",
     "Sub-load component on Day t+1. Summing sub-loads yields total load.",
     "REJECT"),
    ("renewable_share_percent (Day t+1)", "Leakage",
     "Ratio of solar generation to total load on Day t+1. Encodes residual generator dispatch.",
     "REJECT"),
    ("per_capita_load (Day t+1)", "Leakage",
     "Ratio of Day t+1 electrical demand to population. Encodes same-day load.",
     "REJECT"),

    # ── INTRA-DAY ENERGY BALANCE FLOWS (DAY t+1 LEAKAGE) ─────────────────────
    ("solar_generation_kw (Day t+1)", "Leakage",
     "Realized solar power output on Day t+1. Offsets generator dispatch. Unknown until Day t+1 finishes.",
     "REJECT"),
    ("solar_to_load_kwh (Day t+1)", "Leakage",
     "Intra-day energy flow: solar electricity directed to load on Day t+1.",
     "REJECT"),
    ("battery_to_load_kwh (Day t+1)", "Leakage",
     "Intra-day energy flow: battery discharge to load on Day t+1.",
     "REJECT"),
    ("battery_charge_kw (Day t+1)", "Leakage",
     "Intra-day battery charging power on Day t+1.",
     "REJECT"),
    ("battery_discharge_kw (Day t+1)", "Leakage",
     "Intra-day battery discharging power on Day t+1.",
     "REJECT"),
    ("unserved_energy_kwh (Day t+1)", "Leakage",
     "Power deficit on Day t+1. Post-event outcome.",
     "REJECT"),
    ("load_shedding_kwh (Day t+1)", "Leakage",
     "Curtailment dispatched on Day t+1.",
     "REJECT"),
    ("overload_flag (Day t+1)", "Leakage",
     "Post-event binary flag from Day t+1.",
     "REJECT"),
    ("power_shortage_event (Day t+1)", "Leakage",
     "Post-event flag from Day t+1.",
     "REJECT"),
    ("power_margin_kw (Day t+1)", "Leakage",
     "Generation capacity minus load on Day t+1.",
     "REJECT"),
    ("chp_waste_heat_kw (Day t+1)", "Leakage",
     "Thermal output of generators on Day t+1. Replaced by Lag-1 observed CHP heat.",
     "REJECT (Use Lag-1)"),

    # ── FUEL INVENTORY FUTURE OUTCOMES (DAY t+1 LEAKAGE) ─────────────────────
    ("fuel_stock_liters (Day t+1)", "Leakage",
     "End-of-day fuel inventory AFTER Day t+1 consumption. Post-event observation.",
     "REJECT"),
    ("refuel_event (Day t+1)", "Leakage",
     "Whether a fuel tanker transferred fuel during Day t+1. Realized intra-day.",
     "REJECT"),
    ("refuel_quantity_liters (Day t+1)", "Leakage",
     "Volume transferred during Day t+1.",
     "REJECT"),
    ("fuel_received_today_liters (Day t+1)", "Leakage",
     "Fuel liters received during Day t+1.",
     "REJECT"),
    ("fuel_shortage_event (Day t+1)", "Leakage",
     "Fuel outage event recorded during Day t+1.",
     "REJECT"),
    ("fuel_shipment_delayed_today (Day t+1)", "Leakage",
     "Shipping delay notification on Day t+1.",
     "REJECT"),

    # ── SAME-DAY WEATHER OBSERVATIONS (DAY t+1 LEAKAGE) ──────────────────────
    ("temperature_c (Day t+1)", "Leakage",
     "Observed ambient temperature on Day t+1. Replaced by NWP forecast temperature.",
     "REJECT (Use fc_temperature_c)"),
    ("wind_speed_kmh (Day t+1)", "Leakage",
     "Observed wind speed on Day t+1. Replaced by NWP forecast wind.",
     "REJECT (Use fc_wind_speed_kmh)"),
    ("wind_gust_kmh (Day t+1)", "Leakage",
     "Observed wind gust on Day t+1. Replaced by NWP forecast.",
     "REJECT"),
    ("solar_radiation_wm2 (Day t+1)", "Leakage",
     "Realized solar irradiance on Day t+1. Replaced by NWP solar irradiance forecast.",
     "REJECT (Use fc_solar_radiation_wm2)"),
    ("snowfall_cm (Day t+1)", "Leakage",
     "Realized snowfall on Day t+1.",
     "REJECT (Use fc_snowfall_cm)"),
    ("weather_severity (Day t+1)", "Leakage",
     "Meteorological severity observed on Day t+1.",
     "REJECT (Use fc_weather_severity)"),
    ("wind_chill_c (Day t+1)", "Leakage",
     "Computed from Day t+1 realized temperature and wind. Replaced by forecast wind chill.",
     "REJECT (Use fc_wind_chill_c)"),

    # ── POST-EVENT RISK SCORES (DAY t+1 LEAKAGE) ──────────────────────────────
    ("fuel_risk (Day t+1)", "Leakage",
     "Risk score computed at end of Day t+1. Replaced by Lag-1 risk on Day t.",
     "REJECT (Use fuel_risk_lag1)"),
    ("power_risk (Day t+1)", "Leakage",
     "Risk score computed at end of Day t+1.",
     "REJECT (Use power_risk_lag1)"),
    ("overall_risk_score (Day t+1)", "Leakage",
     "Composite risk computed at end of Day t+1.",
     "REJECT (Use overall_risk_lag1)"),

    # ── FORECAST-AVAILABLE SAFE FEATURES (KNOWN BEFORE DAY t+1 BEGINS) ────────
    ("station_enc", "Historical",
     "Static station identifier (Maitri=0, Bharati=1). Physical topology constant.",
     "KEEP"),
    ("month_sin / month_cos", "Forecast Available",
     "Cyclic month encoding for Day t+1. Known astronomically in advance.",
     "KEEP"),
    ("doy_sin / doy_cos", "Forecast Available",
     "Cyclic day-of-year encoding for Day t+1.",
     "KEEP"),
    ("dow_sin / dow_cos", "Forecast Available",
     "Day of week encoding for Day t+1.",
     "KEEP"),
    ("is_shipping_season", "Forecast Available",
     "Antarctic maritime access window (Nov–Mar). Calendar-based.",
     "KEEP"),
    ("is_polar_night / is_polar_day", "Forecast Available",
     "Astronomical flags for Day t+1. Deterministic ephemeris.",
     "KEEP"),
    ("fc_solar_elevation_deg", "Forecast Available",
     "Noon solar elevation angle for Day t+1. Deterministic orbital mechanics.",
     "KEEP"),
    ("fc_solar_daylight_hours", "Forecast Available",
     "Theoretical astronomical daylight duration for Day t+1.",
     "KEEP"),
    ("fc_temperature_c", "Forecast Available",
     "Day-ahead NWP ambient temperature forecast for Day t+1.",
     "KEEP"),
    ("fc_wind_speed_kmh", "Forecast Available",
     "Day-ahead NWP wind speed forecast for Day t+1.",
     "KEEP"),
    ("fc_wind_gust_kmh", "Forecast Available",
     "Day-ahead NWP wind gust forecast for Day t+1.",
     "KEEP"),
    ("fc_solar_radiation_wm2", "Forecast Available",
     "Day-ahead NWP solar irradiance forecast for Day t+1.",
     "KEEP"),
    ("fc_snowfall_cm", "Forecast Available",
     "Day-ahead NWP snowfall precipitation forecast for Day t+1.",
     "KEEP"),
    ("fc_snow_depth_cm", "Forecast Available",
     "Day-ahead NWP snow pack depth forecast for Day t+1.",
     "KEEP"),
    ("fc_weather_severity", "Forecast Available",
     "Day-ahead NWP weather severity forecast for Day t+1.",
     "KEEP"),
    ("fc_weather_type_enc", "Forecast Available",
     "Day-ahead NWP weather regime classification for Day t+1.",
     "KEEP"),
    ("fc_wind_chill_c", "Forecast Available",
     "Thermodynamic wind chill derived from NWP forecast temperature and wind.",
     "KEEP"),
    ("fc_katabatic_index", "Forecast Available",
     "Katabatic wind severity proxy from NWP forecast.",
     "KEEP"),
    ("fc_heating_degree_days", "Forecast Available",
     "Heating demand driver derived from forecast temperature: max(0, 18 - T_fc).",
     "KEEP"),
    ("scheduled_population", "Forecast Available",
     "Pre-planned station crew roster count for Day t+1.",
     "KEEP"),
    ("scheduled_occupancy_pct", "Forecast Available",
     "Scheduled station capacity utilization for Day t+1.",
     "KEEP"),
    ("scheduled_scientists / engineers / medical", "Forecast Available",
     "Crew role breakdown from advance personnel plans for Day t+1.",
     "KEEP"),
    ("fuel_shipments_pending", "Forecast Available",
     "Number of inbound tanker deliveries currently scheduled/in transit.",
     "KEEP"),
    ("fuel_eta_days", "Forecast Available",
     "Estimated days until next scheduled fuel delivery from voyage plan.",
     "KEEP"),

    # ── HISTORICAL TELEMETRY (OBSERVED ON OR BEFORE 18:00 ON DAY t) ───────────
    ("fuel_stock_start_liters", "Historical",
     "Fuel tank level observed at 18:00 cutoff on Day t. This is the numerator of the runway formula evaluated at Day t's consumption rate.",
     "KEEP"),
    ("fuel_stock_lag1", "Historical",
     "Fuel tank level observed on Day t-1.",
     "KEEP"),
    ("fuel_stock_drawdown_3d", "Historical",
     "3-day net fuel inventory reduction rate.",
     "KEEP"),
    ("days_since_refuel_start", "Historical",
     "Elapsed days since last confirmed refueling event (at 18:00 on Day t).",
     "KEEP"),
    ("fuel_lag1", "Historical",
     "Observed fuel consumption on Day t.",
     "KEEP"),
    ("fuel_lag2 / lag3 / lag7 / lag14", "Historical",
     "Observed fuel consumption on Days t-1, t-2, t-6, t-13.",
     "KEEP"),
    ("fuel_roll3/7/14/30_mean", "Historical",
     "Trailing rolling mean fuel consumption: shift-then-roll. Zero look-ahead.",
     "KEEP"),
    ("fuel_expanding_mean", "Historical",
     "Cumulative expanding mean of fuel burn up to Day t.",
     "KEEP"),
    ("fuel_roll7_std / roll14_std", "Historical",
     "Trailing volatility in fuel consumption. Shifted before rolling.",
     "KEEP"),
    ("fuel_trend_3d / fuel_trend_7d", "Historical",
     "Rate of change in fuel burn: fuel_lag1 minus fuel_lag3 or fuel_lag7.",
     "KEEP"),
    ("runway_lag1 / lag2 / lag7", "Historical",
     "Observed fuel_days_remaining on Day t, t-1, t-6. Valid historical telemetry.",
     "KEEP"),
    ("runway_roll3/7/14_mean", "Historical",
     "Trailing rolling mean of observed fuel runway. Shifted before rolling.",
     "KEEP"),
    ("runway_trend_3d / runway_trend_7d", "Historical",
     "Rate of change in fuel runway: runway_lag1 minus runway_lag3 or lag7.",
     "KEEP"),
    ("obs_temp_lag1/2/3", "Historical",
     "Observed ambient temperatures on Days t, t-1, t-2.",
     "KEEP"),
    ("obs_temp_roll7_mean / trend3", "Historical",
     "Trailing rolling mean and trend of observed temperature.",
     "KEEP"),
    ("obs_wind_lag1 / roll7", "Historical",
     "Observed wind speed on Day t and 7-day trailing mean.",
     "KEEP"),
    ("obs_weather_sev_lag1 / roll7", "Historical",
     "Observed weather severity on Day t and 7-day trailing mean.",
     "KEEP"),
    ("pop_lag1 / pop_trend7", "Historical",
     "Actual population on Day t and 7-day population change trend.",
     "KEEP"),
    ("battery_soc_start_pct / soc_lag1 / soc_delta_lag1", "Historical",
     "Battery State of Charge at 18:00 cutoff on Day t. Valid operational snapshot.",
     "KEEP"),
    ("gen_output_lag1 / gen_runtime_lag1", "Historical",
     "Generator output (kW) and runtime (hours) observed on Day t. Not Day t+1.",
     "KEEP"),
    ("gen_utilization_lag1", "Historical",
     "Generator load factor observed on Day t.",
     "KEEP"),
    ("chp_heat_lag1 / chp_heat_roll7_mean", "Historical",
     "Generator waste heat recovered on Day t and 7-day trailing mean.",
     "KEEP"),
    ("fuel_risk_lag1 / power_risk_lag1 / overall_risk_lag1", "Historical",
     "Risk indices observed at end of Day t.",
     "KEEP"),
    ("risk_roll7_mean", "Historical",
     "7-day trailing mean composite station risk index.",
     "KEEP"),
]


def generate_audit_report():
    df = pd.DataFrame(
        AUDIT_RULES,
        columns=["Feature", "Classification", "Reason", "Decision"]
    )
    return df


if __name__ == "__main__":
    df_audit = generate_audit_report()
    out_path = os.path.join(os.path.dirname(__file__), "results_v3", "model3_feature_leakage_audit.csv")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    df_audit.to_csv(out_path, index=False)
    print("=" * 80)
    print("SCIENTIFIC LEAKAGE AUDIT SUMMARY FOR MODEL 3 (FUEL RUNWAY)")
    print("=" * 80)
    print(df_audit["Classification"].value_counts())
    print(f"\nAudit table saved to: {out_path}")
