# leakage_audit.py
# Exhaustive scientific leakage audit for Model 4 (Day-Ahead Inventory Shortage Forecast V3).

import os
import pandas as pd
from config import RESULTS_DIR

AUDIT_RULES = [
    # --- DIRECT TARGET SELF-REFERENCE & SAME-DAY LEAKAGE (DAY t+1) ---
    ("inventory_shortage_items (Day t+1)", "Target Derived",
     "The raw target count on Day t+1. Thresholded (>0) to define inventory_shortage_tomorrow. Cannot appear in features.",
     "REJECT (Predictand)"),
    ("critical_items (Day t+1)", "Leakage",
     "Realized number of items in critical state on Day t+1. Directly determines shortage occurrence.",
     "REJECT"),
    ("low_items (Day t+1)", "Leakage",
     "Realized low inventory count on Day t+1. Same-day realization unknown at 18:00 Day t.",
     "REJECT"),
    ("inventory_health_score (Day t+1)", "Target Derived",
     "Composite score evaluated at 23:59 on Day t+1 reflecting same-day shortages.",
     "REJECT"),
    ("inventory_orders_created_today (Day t+1)", "Leakage",
     "Emergency procurement orders triggered as a direct reaction to Day t+1 shortages.",
     "REJECT"),
    ("received_today (Day t+1)", "Leakage",
     "Deliveries actually received at station during Day t+1. Unknown prior to execution.",
     "REJECT"),
    ("expired_items (Day t+1)", "Leakage",
     "Realized batch expirations occurring during Day t+1. Unknown at 18:00 on Day t.",
     "REJECT"),
    ("expired_quantity (Day t+1)", "Leakage",
     "Quantity of food/medical batches discarded during Day t+1.",
     "REJECT"),
    ("delayed_shipments (Day t+1)", "Leakage",
     "Realized shipment delay status updated after intra-day logistics event.",
     "REJECT"),
    ("inventory_risk (Day t+1)", "Target Derived",
     "Calculated post-event using Day t+1 realized shortages and health.",
     "REJECT"),
    ("unmet_demand (Day t+1)", "Target Derived",
     "Realized unfulfilled item requests occurring during Day t+1.",
     "REJECT"),
    ("actual_consumption (Day t+1)", "Leakage",
     "Realized item consumption by station personnel during Day t+1.",
     "REJECT"),
    ("power_shortage_event (Day t+1)", "Leakage",
     "Power outage occurring during Day t+1. Cannot be known at Day t cutoff.",
     "REJECT"),
    ("water_shortage_event (Day t+1)", "Leakage",
     "Water plant failure occurring during Day t+1.",
     "REJECT"),
    ("generator_runtime_hours (Day t+1)", "Leakage",
     "Total genset operational hours on Day t+1.",
     "REJECT"),
    ("active_generators (Day t+1)", "Leakage",
     "Generator staging dispatch during Day t+1.",
     "REJECT"),
    ("total_load_kw (Day t+1)", "Leakage",
     "Realized station electrical demand on Day t+1.",
     "REJECT"),
    ("temperature_c (Day t+1 realized)", "Leakage",
     "Same-day weather observation. Must use day-ahead NWP forecast instead.",
     "REJECT (Replaced by fc_temperature_c)"),
    ("wind_speed_kmh (Day t+1 realized)", "Leakage",
     "Same-day wind observation. Must use day-ahead NWP forecast instead.",
     "REJECT (Replaced by fc_wind_speed_kmh)"),

    # --- HISTORICAL TELEMETRY (KNOWN AT 18:00 ON DAY t) ---
    ("inv_health_lag0", "Historical",
     "Observed inventory health score at 18:00 cutoff on Day t. Valid leading indicator.",
     "ACCEPT"),
    ("inv_health_lag1", "Historical",
     "Inventory health score observed on Day t-1.",
     "ACCEPT"),
    ("inv_health_roll7_mean", "Historical",
     "7-day trailing rolling mean of inventory health ending on Day t. Strict shift-then-roll.",
     "ACCEPT"),
    ("inv_health_roll14_mean", "Historical",
     "14-day trailing rolling mean of inventory health ending on Day t.",
     "ACCEPT"),
    ("inv_health_trend_7d", "Historical",
     "7-day change in inventory health: health[t] - health[t-7].",
     "ACCEPT"),
    ("critical_items_lag0", "Historical",
     "Count of critical items observed at 18:00 on Day t.",
     "ACCEPT"),
    ("critical_items_lag1", "Historical",
     "Critical items observed on Day t-1.",
     "ACCEPT"),
    ("critical_items_roll7_mean", "Historical",
     "7-day trailing rolling mean of critical items ending on Day t.",
     "ACCEPT"),
    ("low_items_lag0", "Historical",
     "Count of low-stock items observed at 18:00 on Day t.",
     "ACCEPT"),
    ("low_items_lag1", "Historical",
     "Low-stock items observed on Day t-1.",
     "ACCEPT"),
    ("low_items_roll7_mean", "Historical",
     "7-day trailing rolling mean of low-stock items ending on Day t.",
     "ACCEPT"),
    ("shortage_items_lag0", "Historical",
     "Number of items in shortage observed on Day t.",
     "ACCEPT"),
    ("shortage_items_lag1", "Historical",
     "Number of items in shortage observed on Day t-1.",
     "ACCEPT"),
    ("shortage_items_lag2", "Historical",
     "Number of items in shortage observed on Day t-2.",
     "ACCEPT"),
    ("shortage_items_lag7", "Historical",
     "Number of items in shortage observed on Day t-7.",
     "ACCEPT"),
    ("shortage_items_lag14", "Historical",
     "Number of items in shortage observed on Day t-14.",
     "ACCEPT"),
    ("shortage_roll3_mean", "Historical",
     "3-day trailing rolling average of shortages ending on Day t.",
     "ACCEPT"),
    ("shortage_roll7_mean", "Historical",
     "7-day trailing rolling average of shortages ending on Day t.",
     "ACCEPT"),
    ("shortage_roll14_mean", "Historical",
     "14-day trailing rolling average of shortages ending on Day t.",
     "ACCEPT"),
    ("shortage_roll30_mean", "Historical",
     "30-day trailing rolling average of shortages ending on Day t.",
     "ACCEPT"),
    ("shortage_trend_7d", "Historical",
     "7-day trend in shortages: shortage[t] - shortage[t-7].",
     "ACCEPT"),
    ("shortage_binary_lag0", "Historical",
     "Binary flag: was station in shortage on Day t?",
     "ACCEPT"),
    ("shortage_days_in_past_7", "Historical",
     "Count of shortage days in the trailing 7 days [t-6 .. t].",
     "ACCEPT"),
    ("shortage_days_in_past_30", "Historical",
     "Count of shortage days in the trailing 30 days [t-29 .. t].",
     "ACCEPT"),
    ("inv_batch_count_lag0", "Historical",
     "Active storage batch count observed at 18:00 on Day t.",
     "ACCEPT"),
    ("expired_items_lag0", "Historical",
     "Known expired items recorded at or before 18:00 on Day t.",
     "ACCEPT"),
    ("expired_quantity_lag0", "Historical",
     "Cumulative expired stock volume recorded at or before Day t.",
     "ACCEPT"),
    ("inventory_risk_lag0", "Historical",
     "Inventory risk score observed at 18:00 on Day t.",
     "ACCEPT"),
    ("inv_risk_roll7_mean", "Historical",
     "7-day trailing average inventory risk score ending on Day t.",
     "ACCEPT"),
    ("risk_score_lag0", "Historical",
     "Overall station composite risk score at 18:00 on Day t.",
     "ACCEPT"),
    ("station_health_lag0", "Historical",
     "Overall station health metric observed at 18:00 on Day t.",
     "ACCEPT"),

    # --- INBOUND SUPPLY CHAIN & SHIPPING CONSTRAINTS (KNOWN AT DAY t) ---
    ("inv_orders_pending_lag0", "Historical",
     "Number of active pending supply orders logged in ERP at Day t.",
     "ACCEPT"),
    ("inv_eta_days_lag0", "Historical",
     "Estimated delivery days remaining for next scheduled supply vessel at Day t.",
     "ACCEPT"),
    ("delayed_shipments_lag0", "Historical",
     "Number of inbound shipments marked delayed as of Day t.",
     "ACCEPT"),
    ("days_since_shipment_received", "Historical",
     "Elapsed calendar days since previous supply shipment arrived at station.",
     "ACCEPT"),
    ("is_shipping_season", "Forecast Available",
     "Calendar indicator for Antarctic austral summer sea-ice navigation window (Nov-Mar).",
     "ACCEPT"),
    ("days_into_shipping_season", "Forecast Available",
     "Days elapsed into current shipping season window.",
     "ACCEPT"),
    ("days_until_shipping_season", "Forecast Available",
     "Days remaining until next shipping season window opens.",
     "ACCEPT"),
    ("shipping_window_open", "Forecast Available",
     "Binary constraint indicating whether physical resupply is geographically possible.",
     "ACCEPT"),

    # --- SCHEDULED POPULATION ROSTER (ADVANCE MANIFEST FOR DAY t+1) ---
    ("scheduled_population", "Forecast Available",
     "Crew roster scheduled for Day t+1 filed in advance. Primary consumption driver.",
     "ACCEPT"),
    ("scheduled_occupancy_percent", "Forecast Available",
     "Scheduled station bed occupancy percentage for Day t+1.",
     "ACCEPT"),
    ("scheduled_scientists", "Forecast Available",
     "Scheduled research staff count for Day t+1 (drives lab consumables demand).",
     "ACCEPT"),
    ("scheduled_engineers", "Forecast Available",
     "Scheduled engineering crew count for Day t+1 (drives maintenance spares demand).",
     "ACCEPT"),
    ("scheduled_technicians", "Forecast Available",
     "Scheduled technical staff count for Day t+1.",
     "ACCEPT"),
    ("scheduled_logistics", "Forecast Available",
     "Scheduled logistics personnel for Day t+1.",
     "ACCEPT"),
    ("scheduled_medical", "Forecast Available",
     "Scheduled medical personnel for Day t+1.",
     "ACCEPT"),
    ("pop_lag1", "Historical",
     "Actual population on Day t-1.",
     "ACCEPT"),
    ("pop_roll14_mean", "Historical",
     "14-day trailing mean population ending on Day t.",
     "ACCEPT"),
    ("pop_trend_7d", "Historical",
     "7-day population change: pop[t] - pop[t-7].",
     "ACCEPT"),

    # --- DAY-AHEAD NWP WEATHER FORECAST (PUBLISHED FOR DAY t+1) ---
    ("fc_temperature_c", "Forecast Available",
     "Day-ahead NWP surface temperature forecast for Day t+1.",
     "ACCEPT"),
    ("fc_wind_speed_kmh", "Forecast Available",
     "Day-ahead NWP wind speed forecast for Day t+1.",
     "ACCEPT"),
    ("fc_wind_gust_kmh", "Forecast Available",
     "Day-ahead NWP peak gust forecast for Day t+1.",
     "ACCEPT"),
    ("fc_weather_severity", "Forecast Available",
     "Day-ahead NWP storm severity index for Day t+1 (affects transport and heating).",
     "ACCEPT"),
    ("fc_solar_radiation_wm2", "Forecast Available",
     "Day-ahead forecasted solar irradiance for Day t+1.",
     "ACCEPT"),
    ("fc_solar_daylight_hours", "Forecast Available",
     "Astronomically computed daylight hours for Day t+1.",
     "ACCEPT"),
    ("fc_heating_degree_days", "Forecast Available",
     "Forecasted thermal demand metric: max(0, 18 - fc_temperature_c).",
     "ACCEPT"),
    ("fc_blizzard_risk", "Forecast Available",
     "Forecasted blizzard risk indicator for Day t+1.",
     "ACCEPT"),
    ("fc_is_extreme_weather", "Forecast Available",
     "Binary flag for severe weather conditions on Day t+1.",
     "ACCEPT"),

    # --- EQUIPMENT & MAINTENANCE DEMAND PROXIES (OBSERVED ON DAY t) ---
    ("gen_runtime_lag0", "Historical",
     "Generator runtime on Day t (proxy for mechanical wear and spare parts burn).",
     "ACCEPT"),
    ("gen_output_lag0", "Historical",
     "Generator electrical output on Day t.",
     "ACCEPT"),
    ("active_gen_lag0", "Historical",
     "Active generator units operating on Day t.",
     "ACCEPT"),
    ("power_risk_lag0", "Historical",
     "Power subsystem risk score observed at 18:00 Day t (predicts spare parts draw).",
     "ACCEPT"),
    ("water_risk_lag0", "Historical",
     "Water subsystem risk score observed at 18:00 Day t (predicts filter/chemical draw).",
     "ACCEPT"),
    ("fuel_risk_lag0", "Historical",
     "Fuel subsystem risk score observed at 18:00 Day t.",
     "ACCEPT"),
    ("water_plant_util_lag0", "Historical",
     "Water plant utilization rate on Day t.",
     "ACCEPT"),
    ("station_enc", "Historical",
     "Station identity encoding (Bharati = 0, Maitri = 1).",
     "ACCEPT"),
    ("month_sin", "Forecast Available",
     "Trigonometric annual seasonal cycle component for Day t+1.",
     "ACCEPT"),
    ("month_cos", "Forecast Available",
     "Trigonometric annual seasonal cycle component for Day t+1.",
     "ACCEPT"),
    ("doy_sin", "Forecast Available",
     "Day-of-year harmonic seasonal component for Day t+1.",
     "ACCEPT"),
    ("doy_cos", "Forecast Available",
     "Day-of-year harmonic seasonal component for Day t+1.",
     "ACCEPT"),
    ("season_enc", "Forecast Available",
     "Astronomical season encoding (Summer = 0, Winter = 1) for Day t+1.",
     "ACCEPT"),
    ("is_polar_night", "Forecast Available",
     "Binary astronomical flag for continuous 24h darkness on Day t+1.",
     "ACCEPT"),
    ("is_polar_day", "Forecast Available",
     "Binary astronomical flag for continuous 24h daylight on Day t+1.",
     "ACCEPT"),
]


def generate_leakage_audit_table() -> pd.DataFrame:
    df = pd.DataFrame(AUDIT_RULES, columns=["Feature", "Classification", "Reason", "Decision"])
    out_path = os.path.join(RESULTS_DIR, "model4_feature_leakage_audit.csv")
    df.to_csv(out_path, index=False)
    print(f"[LeakageAudit] Audit saved: {out_path} ({len(df)} candidate variables audited)")
    return df


if __name__ == "__main__":
    generate_leakage_audit_table()
